server:
  servlet:
    context-path: '/pizzaordering '
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/pizzaordering?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: 'true '
  sql:
    init:
      mode: always
